# Loops in Python

# i = 1
# while i <=100:
#     print(i)
#     i += 1


# print("hundred complete")

# i = 100
# while i >=1:
#     print(i)
#     i -= 1


# print("hundred complete")

# multipication loop
# n = int(input("enter number"))
# i= 1
# while i <= 10 :
#     print(n*i)
#     i += 1

# nums = [1 ,4, 9, 16, 25, 36, 49, 64, 81, 100]


# idx = 0
# while idx < len(nums) :
#     print(nums[idx])
#     idx += 1

# nums = (1 ,4, 9, 16, 25, 36, 49, 64, 81, 100)

# x = 49

# i = 0
# while i < len(nums):
#    if(nums[i] == x):
#        print("found ", i)
#    i += 1

# break 

# i = 1
# while i <= 5:
#     print(i)
#     if(i == 3):
#        break 
#     i += 1

# print("break program")  


# i = 1
# while i <= 5:
   
#     if(i == 3):
#        i += 1
#        continue
#     print(i)
#     i += 1

# print("skip program")  

# for loops

# nums = [1,2,3,4,5,6,7]
# nums = (1,2,3,4,5,6,7)
# for val in nums :
#     print(val)

# str = "apnacollege"

# for char in str :
#     print(char)

# nums = [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

# for val in nums: 
#             print (val)


# for i in range(1,101,1):
#     print(i)

# for i in range (100, 0 , -1):
#     print(i)

# n = int(input())

# for i in range(1, 11):
#       print(n *i)

# pass statements

# for i in range (5):
#    pass

# print("sum of numbers")

# lets practice
# WAP find the sum of natural numbers.(using while loops)

# n = 20000

# sum = 0 
# for i in range(1, n+1):
#  sum += i
# print("total sum",sum)  

# n= 10
# sum =0
# i=1
# while i<=n :
#     sum +=i
#     i +=1
# print("total sum",sum)



# WAP to find the factorial of first n numbers. (using for)

# n= 10
# fact =1
# i=1
# while i<=n :
#     fact *=i
#     i +=1
# print("factorial",fact)

