# marks1 =   94.4
# marks2 =   84.4
# marks3 =   74.4
# marks4 =   64.4
# marks5 =   44.4

#  List 

# marks = [94 ,87, 78, 69, 50]

# print(marks)
# print(type(marks))
# print(len(marks))
# print(marks[2])


# student = ["karan", 95, 67, "delhi"]
# print(student[5])
# student[0] = "Arjun"
# print(student)

# list slicing

# # append
# list = [2,1,3]
# list.append(4)
# print(list)

# # sort
# list.sort()
# print(list)

# # sort reverse
# list.sort(reverse=True)
# print(list)

# # reverse
# list.reverse()
# print(list)

# # insert
# list.insert(0,5)
# print(list)


# #  Tuple Methods
# tup = (87, 64, 76, 95, 67)
# print(tup)
# print(type(tup))

# print(tup.index(67))

# print(tup.count(76))

# lets practis

# movies =[]
# mov1 = input("enter 1st movies")
# mov2 = input("enter 2nd movies")
# mov3 = input("enter 1rd movies")

# movies.append(mov1)
# movies.append(mov2)
# movies.append(mov3)
   
# print(movies)

# list1 = ("m", "a", "a", "m", "p")
# copy_list1 = list1.copy()
# copy_list1.reverse()

# if (copy_list1 == list1 ):
#     print("pailumdrom")
# else :
#     print("not palidrum")    